/* ==========================================================================
   FUNDSLEUTH GLOBAL SIMPLE MODE ENGINE (Aa Simple Mode)
   Rewrites technical financial jargon into plain, beginner-friendly terms.
   ========================================================================== */

(function () {
    const SIMPLE_DICTIONARY = {
        'Standard Deviation': {
            simple: 'Shows how much the fund’s returns move up and down over time.',
            why: 'Higher movement means higher short-term ups and downs for your money.',
            spoken: 'Standard deviation shows how much the fund’s returns move up and down over time.'
        },
        'Sharpe Ratio': {
            simple: 'Shows how much extra return you get for each unit of risk taken.',
            why: 'A higher number means the fund manager generates better returns without taking reckless risk.',
            spoken: 'Sharpe ratio shows how much extra return you get for each unit of risk taken.'
        },
        'Expense Ratio': {
            simple: 'The annual management fee deducted directly from your fund value.',
            why: 'Lower expense ratio means more of your money stays invested and grows.',
            spoken: 'Expense ratio is the annual fee deducted from your fund value. Lower is better.'
        },
        'Beta': {
            simple: 'Measures how sensitively the fund reacts when the stock market moves.',
            why: 'Beta above 1 means the fund moves faster than the market; below 1 means it is calmer.',
            spoken: 'Beta measures how sensitively the fund reacts to market movements.'
        },
        'Alpha': {
            simple: 'The bonus return generated by the fund manager compared to the benchmark index.',
            why: 'Positive alpha means the fund manager outperformed the market index.',
            spoken: 'Alpha is the bonus return generated by the fund manager compared to the benchmark.'
        },
        'Portfolio Overlap': {
            simple: 'When multiple mutual funds in your portfolio hold the exact same company stocks.',
            why: 'High overlap reduces real diversification and concentrates your risk in a few stocks.',
            spoken: 'Portfolio overlap occurs when your funds hold the exact same underlying company stocks.'
        },
        'Sector Concentration': {
            simple: 'When too much of your money is invested in one single industry (like Banks or Tech).',
            why: 'If that one industry faces bad news, a large portion of your portfolio suffers.',
            spoken: 'Sector concentration means having too much money invested in a single industry.'
        },
        'Exit Load': {
            simple: 'A fee charged if you withdraw or sell your fund units too quickly.',
            why: 'Encourages long-term investing and protects remaining investors from early withdrawals.',
            spoken: 'Exit load is a fee charged if you withdraw your money before the minimum period.'
        }
    };

    class SimpleModeManager {
        constructor() {
            this.enabled = localStorage.getItem('fundsleuth_pref_simple_mode') === 'true';
            this.init();
        }

        init() {
            this.applyState();
        }

        toggle() {
            this.enabled = !this.enabled;
            localStorage.setItem('fundsleuth_pref_simple_mode', this.enabled ? 'true' : 'false');
            this.applyState();

            if (window.showToast) {
                const label = this.enabled ? 'Aa Simple Mode Enabled (Beginner-Friendly Terms)' : 'Standard Technical View Enabled';
                window.showToast(label, 'info');
            }
        }

        applyState() {
            document.body.classList.toggle('simple-mode-active', this.enabled);
            const badge = document.getElementById('simpleModeBadge');
            if (badge) {
                badge.innerText = this.enabled ? 'Aa Simple: ON' : 'Aa Simple: OFF';
                badge.className = this.enabled ? 'badge bg-success text-white font-mono rounded-pill' : 'badge bg-secondary bg-opacity-20 text-secondary font-mono rounded-pill';
            }
            this.updateDOMTexts();
        }

        getExplanation(term) {
            return SIMPLE_DICTIONARY[term] || null;
        }

        updateDOMTexts() {
            if (!this.enabled) return;
            document.querySelectorAll('[data-simple-term]').forEach(el => {
                const term = el.getAttribute('data-simple-term');
                const info = this.getExplanation(term);
                if (info) {
                    el.setAttribute('title', info.simple);
                }
            });
        }
    }

    document.addEventListener('DOMContentLoaded', () => {
        window.simpleModeManager = new SimpleModeManager();
    });
})();
